swipe:
  3:
    left:
      command: 'xdotool key Super_L+ctrl+Right'
    right:
      command: 'xdotool key Super_L+ctrl+Left'
    up:
      command: 'xdotool key ctrl+F8'
    down:
      command: 'xdotool key ctrl+F8'
  
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'
