swipe:
  3:
    left:
     command: "xdotool key super+bracketleft"
    right:
     command: "xdotool key super+bracketright"
    up:
     command: "xdotool key super+f"
    down:
     command: "xdotool key super+t"

pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'
