swipe:
  3:
    left:
     command: exec i3 workspace next
    right:
      command: exec i3 workspace prev
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 floating toggle


pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'
