{
  pkgs,
  lib,
  config,
  ...
}: let
  inherit (config.lib.stylix) colors;

  # Generate a proper Neovim colorscheme using Stylix base16 colors
  stylixColorscheme = pkgs.writeText "stylix.lua" ''
    -- Stylix colorscheme for Neovim
    -- Auto-generated by Nix from Stylix base16 colors

    vim.cmd("hi clear")
    if vim.fn.exists("syntax_on") then
      vim.cmd("syntax reset")
    end

    vim.g.colors_name = "stylix"

    local colors = {
      base00 = "#${colors.base00}", -- Default Background
      base01 = "#${colors.base01}", -- Lighter Background
      base02 = "#${colors.base02}", -- Selection Background
      base03 = "#${colors.base03}", -- Comments
      base04 = "#${colors.base04}", -- Dark Foreground
      base05 = "#${colors.base05}", -- Default Foreground
      base06 = "#${colors.base06}", -- Light Foreground
      base07 = "#${colors.base07}", -- Light Background
      base08 = "#${colors.base08}", -- Red
      base09 = "#${colors.base09}", -- Orange
      base0A = "#${colors.base0A}", -- Yellow
      base0B = "#${colors.base0B}", -- Green
      base0C = "#${colors.base0C}", -- Cyan
      base0D = "#${colors.base0D}", -- Blue
      base0E = "#${colors.base0E}", -- Purple/Magenta
      base0F = "#${colors.base0F}", -- Brown
    }

    local hi = function(group, opts)
      vim.api.nvim_set_hl(0, group, opts)
    end

    -- Editor
    hi("Normal", { fg = colors.base05, bg = "NONE" })
    hi("NormalNC", { fg = colors.base05, bg = "NONE" })
    hi("NormalFloat", { fg = colors.base05, bg = colors.base00 })
    hi("FloatBorder", { fg = colors.base03, bg = colors.base00 })
    hi("ColorColumn", { bg = "NONE" })
    hi("Cursor", { fg = colors.base00, bg = colors.base05 })
    hi("CursorLine", { bg = colors.base00 })
    hi("CursorColumn", { bg = colors.base00 })
    hi("LineNr", { fg = colors.base03 })
    hi("CursorLineNr", { fg = colors.base0A, bold = true })
    hi("SignColumn", { fg = colors.base03, bg = "NONE" })
    hi("VertSplit", { fg = colors.base02 })
    hi("WinSeparator", { fg = colors.base02 })
    hi("Folded", { fg = colors.base03, bg = colors.base01 })
    hi("FoldColumn", { fg = colors.base03, bg = "NONE" })
    hi("EndOfBuffer", { fg = colors.base00, bg = "NONE" })

    -- Search
    hi("Search", { fg = colors.base00, bg = colors.base0A })
    hi("IncSearch", { fg = colors.base00, bg = colors.base09 })
    hi("CurSearch", { fg = colors.base00, bg = colors.base09 })
    hi("Substitute", { fg = colors.base00, bg = colors.base0A })

    -- Popup/Completion
    hi("Pmenu", { fg = colors.base05, bg = colors.base01 })
    hi("PmenuSel", { fg = colors.base00, bg = colors.base0D })
    hi("PmenuSbar", { bg = colors.base02 })
    hi("PmenuThumb", { bg = colors.base04 })

    -- Statusline
    hi("StatusLine", { fg = colors.base05, bg = colors.base00 })
    hi("StatusLineNC", { fg = colors.base04, bg = colors.base00 })
    hi("TabLine", { fg = colors.base04, bg = colors.base01 })
    hi("TabLineFill", { bg = colors.base01 })
    hi("TabLineSel", { fg = colors.base05, bg = colors.base00 })

    -- Messages
    hi("ModeMsg", { fg = colors.base0B })
    hi("MoreMsg", { fg = colors.base0B })
    hi("Question", { fg = colors.base0D })
    hi("WarningMsg", { fg = colors.base08 })
    hi("ErrorMsg", { fg = colors.base08, bg = colors.base00 })

    -- Visual
    hi("Visual", { bg = colors.base02 })
    hi("VisualNOS", { bg = colors.base02 })

    -- Diff
    hi("DiffAdd", { fg = colors.base0B, bg = colors.base01 })
    hi("DiffChange", { fg = colors.base0A, bg = colors.base01 })
    hi("DiffDelete", { fg = colors.base08, bg = colors.base01 })
    hi("DiffText", { fg = colors.base0D, bg = colors.base01 })

    -- Spell
    hi("SpellBad", { undercurl = true, sp = colors.base08 })
    hi("SpellCap", { undercurl = true, sp = colors.base0A })
    hi("SpellLocal", { undercurl = true, sp = colors.base0C })
    hi("SpellRare", { undercurl = true, sp = colors.base0E })

    -- Syntax
    hi("Comment", { fg = colors.base03, italic = true })
    hi("Constant", { fg = colors.base09 })
    hi("String", { fg = colors.base0B })
    hi("Character", { fg = colors.base0B })
    hi("Number", { fg = colors.base09 })
    hi("Boolean", { fg = colors.base09 })
    hi("Float", { fg = colors.base09 })
    hi("Identifier", { fg = colors.base08 })
    hi("Function", { fg = colors.base0D })
    hi("Statement", { fg = colors.base0E })
    hi("Conditional", { fg = colors.base0E })
    hi("Repeat", { fg = colors.base0E })
    hi("Label", { fg = colors.base0A })
    hi("Operator", { fg = colors.base05 })
    hi("Keyword", { fg = colors.base0E })
    hi("Exception", { fg = colors.base08 })
    hi("PreProc", { fg = colors.base0A })
    hi("Include", { fg = colors.base0D })
    hi("Define", { fg = colors.base0E })
    hi("Macro", { fg = colors.base0A })
    hi("PreCondit", { fg = colors.base0A })
    hi("Type", { fg = colors.base0A })
    hi("StorageClass", { fg = colors.base0A })
    hi("Structure", { fg = colors.base0A })
    hi("Typedef", { fg = colors.base0A })
    hi("Special", { fg = colors.base0C })
    hi("SpecialChar", { fg = colors.base0F })
    hi("Tag", { fg = colors.base0A })
    hi("Delimiter", { fg = colors.base05 })
    hi("SpecialComment", { fg = colors.base03 })
    hi("Debug", { fg = colors.base08 })
    hi("Underlined", { underline = true })
    hi("Error", { fg = colors.base08 })
    hi("Todo", { fg = colors.base0A, bg = colors.base01 })

    -- Treesitter
    hi("@variable", { fg = colors.base05 })
    hi("@variable.builtin", { fg = colors.base09 })
    hi("@variable.parameter", { fg = colors.base08, italic = true })
    hi("@variable.member", { fg = colors.base05 })
    hi("@constant", { fg = colors.base09 })
    hi("@constant.builtin", { fg = colors.base09 })
    hi("@constant.macro", { fg = colors.base0A })
    hi("@module", { fg = colors.base05 })
    hi("@label", { fg = colors.base0A })
    hi("@string", { fg = colors.base0B })
    hi("@string.escape", { fg = colors.base0C })
    hi("@string.special", { fg = colors.base0C })
    hi("@character", { fg = colors.base0B })
    hi("@number", { fg = colors.base09 })
    hi("@boolean", { fg = colors.base09 })
    hi("@float", { fg = colors.base09 })
    hi("@function", { fg = colors.base0D })
    hi("@function.builtin", { fg = colors.base0C })
    hi("@function.macro", { fg = colors.base0A })
    hi("@function.method", { fg = colors.base0D })
    hi("@constructor", { fg = colors.base0C })
    hi("@keyword", { fg = colors.base0E })
    hi("@keyword.function", { fg = colors.base0E })
    hi("@keyword.operator", { fg = colors.base0E })
    hi("@keyword.return", { fg = colors.base0E })
    hi("@operator", { fg = colors.base05 })
    hi("@punctuation.bracket", { fg = colors.base05 })
    hi("@punctuation.delimiter", { fg = colors.base05 })
    hi("@punctuation.special", { fg = colors.base05 })
    hi("@type", { fg = colors.base0A })
    hi("@type.builtin", { fg = colors.base0A })
    hi("@type.definition", { fg = colors.base0A })
    hi("@type.qualifier", { fg = colors.base0E })
    hi("@attribute", { fg = colors.base0A })
    hi("@property", { fg = colors.base0C })
    hi("@comment", { fg = colors.base03, italic = true })
    hi("@tag", { fg = colors.base0F })
    hi("@tag.attribute", { fg = colors.base0A })
    hi("@tag.delimiter", { fg = colors.base0F })

    -- LSP
    hi("DiagnosticError", { fg = colors.base08 })
    hi("DiagnosticWarn", { fg = colors.base0A })
    hi("DiagnosticInfo", { fg = colors.base0D })
    hi("DiagnosticHint", { fg = colors.base0C })
    hi("DiagnosticUnderlineError", { undercurl = true, sp = colors.base08 })
    hi("DiagnosticUnderlineWarn", { undercurl = true, sp = colors.base0A })
    hi("DiagnosticUnderlineInfo", { undercurl = true, sp = colors.base0D })
    hi("DiagnosticUnderlineHint", { undercurl = true, sp = colors.base0C })
    hi("LspReferenceText", { bg = colors.base02 })
    hi("LspReferenceRead", { bg = colors.base02 })
    hi("LspReferenceWrite", { bg = colors.base02 })

    -- Git
    hi("GitSignsAdd", { fg = colors.base0B })
    hi("GitSignsChange", { fg = colors.base0A })
    hi("GitSignsDelete", { fg = colors.base08 })

    -- NeoTree
    hi("NeoTreeNormal", { fg = colors.base05, bg = "NONE" })
    hi("NeoTreeNormalNC", { fg = colors.base05, bg = "NONE" })
    hi("NeoTreeDirectoryIcon", { fg = colors.base0D })
    hi("NeoTreeDirectoryName", { fg = colors.base0D })
    hi("NeoTreeRootName", { fg = colors.base0E, bold = true })
    hi("NeoTreeGitAdded", { fg = colors.base0B })
    hi("NeoTreeGitModified", { fg = colors.base0A })
    hi("NeoTreeGitDeleted", { fg = colors.base08 })

    -- Telescope
    hi("TelescopeBorder", { fg = colors.base03 })
    hi("TelescopePromptBorder", { fg = colors.base03 })
    hi("TelescopeResultsBorder", { fg = colors.base03 })
    hi("TelescopePreviewBorder", { fg = colors.base03 })
    hi("TelescopeSelection", { fg = colors.base05, bg = colors.base02 })
    hi("TelescopeSelectionCaret", { fg = colors.base0D })
    hi("TelescopeMatching", { fg = colors.base0A, bold = true })

    -- Which-key
    hi("WhichKey", { fg = colors.base0D })
    hi("WhichKeyGroup", { fg = colors.base0E })
    hi("WhichKeySeparator", { fg = colors.base03 })
    hi("WhichKeyDesc", { fg = colors.base05 })

    -- Indent Blankline
    hi("IblIndent", { fg = colors.base02 })
    hi("IblScope", { fg = colors.base04 })
  '';
in {
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    withNodeJs = true;
    withPython3 = true;
  };

  # Setup AstroNvim
  # 1. Clone AstroNvim template if not present
  # 2. Link our user config
  # 3. Copy stylix colorscheme
  home.activation.installAstroNvim = lib.hm.dag.entryAfter ["writeBoundary"] ''
    if [ ! -d "$HOME/.config/nvim" ]; then
      ${pkgs.git}/bin/git clone --depth 1 https://github.com/AstroNvim/template "$HOME/.config/nvim"
    fi

    # Check if the link exists or if it is a directory
    if [ -e "$HOME/.config/nvim/lua" ]; then
       if [ ! -L "$HOME/.config/nvim/lua" ]; then
          echo "Warning: Replacing $HOME/.config/nvim/lua with custom config"
          rm -rf "$HOME/.config/nvim/lua"
       fi
    fi

    # Re-link every time to ensure it points to the correct store path
    ln -sfn ${../../../astronvim_config/lua} $HOME/.config/nvim/lua

    # Create colors directory and copy stylix colorscheme (force overwrite)
    mkdir -p "$HOME/.config/nvim/colors"
    ${pkgs.coreutils}/bin/install -m 644 ${stylixColorscheme} "$HOME/.config/nvim/colors/stylix.lua"
  '';
}
