format = """
$os\
[ for ]()\
$username\
$directory\
$git_branch\
$git_status\
$c\
$golang\
$nodejs\
$nim\
$rust\
$scala\
$docker_context
$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '#007DFF'
green = '#00DE36'
mustard = '#af8700'
orange = '#FC7E4B'


# You can also replace your username using a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:blue"
style_root = "fg:blue"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false # Disabled by default

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[directory]
style = "fg:green"
format = "[in $path ]($style)"
truncation_length = 3
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = " "
"Documents" = "  "
"Downloads" = "  "
"Pictures" = "  "
"Github" = "  "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[git_branch]
symbol = ""
style = "fg:#E54C2D"
format = '[on $symbol $branch]($style)'

[git_status]
style = "fg:yellow"
format = '[ \[$all_status$ahead_behind\]]($style)'

[c]
symbol = ""
style = "fg:#000000"
format = '[ using $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "fg:#0DAEE1"
format = '[ using $symbol $context ]($style) $path'

[golang]
symbol = ""
style = "fg:#65CAD8"
format = '[ using $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#398037"
format = '[ using $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#AF4301"
format = '[ using $symbol ($version) ]($style)'

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[](bold red) '
