#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

### Startup

# Dual Screen
xrandr --output DVI-D-0 --primary --left-of HDMI-A-0 --auto

# Wallpaper
feh --bg-fill ~/Pictures/bspwm/*

# Fusuma
pgrep fusuma || fusuma -d

# Compositor
pgrep picom || picom --experimental-backend &

# Clipboard history
pgrep clipit || clipit &

# Network
nm-applet &

# Policy Kit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Nvidia Setting (fix screen tear)
# nvidia-settings --assign CurrentMetaMode="$(nvidia-settings -q CurrentMetaMode -t|tr '\n' ' '|sed -e 's/.*:: \(.*\)/\1\n/g' -e 's/}/, ForceCompositionPipeline = On}/g')" > /dev/null

# Polybar
"$HOME"/.config/polybar/launch.sh &

# Map capslock to esc
setxkbmap -option caps:escape

# bspwm stuff
bspc monitor DVI-D-0 -d 󰇊 󰇋 󰇌 󰇍 󰇎 󰇏

### bspwm config
bspc config border_width 2
bspc config window_gap 20

bspc config active_border_color "#e87917"
bspc config focused_border_color "#e87917"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

bspc config split_ratio 0.50
bspc config focus_follows_pointer true
bspc config single_monocle true
bspc config history_aware_focus true

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_sidie

### window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
