[buildPlans.MeraIosevka]
family = "MeraIosevka"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.MeraIosevka.variants.design]
capital-g = "toothless-corner-serifless-hooked"
capital-q = "detached-bend-tailed"
capital-w = "straight-vertical-sides-serifless"
a = "double-storey-serifless"
f = "diagonal-tailed-crossbar-at-x-height"
g = "double-storey"
k = "diagonal-tailed-cursive-serifless"
l = "serifed-diagonal-tailed"
t = "diagonal-tailed"
w = "straight-vertical-sides-serifless"
zero = "dotted"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "upright-flat"
eight = "two-circles"
guillemet = "straight"
ampersand = "lower-open"
at = "fourfold"
dollar = "open"
cent = "open-cap"
bar = "force-upright"
question = "corner"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.MeraIosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.MeraIosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.MeraIosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.MeraIosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.MeraIosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
