[buildPlans.MeraIosevka]
family = "Mera Iosevka"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.MeraIosevka.variants]
inherits = "ss03"

[buildPlans.MeraIosevka.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hookless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-m = "hanging-serifless"
capital-n = "asymmetric-serifless"
capital-p = "closed-serifless"
capital-q = "detached-bend-tailed"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
a = "single-storey-earless-rounded-serifed"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "diagonal-tailed"
g = "double-storey"
i = "diagonal-tailed"
j = "diagonal-tailed-serifless"
k = "cursive-serifless"
l = "diagonal-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-tailed-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "diagonal-tailed-short-neck2"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "straight-vertical-sides-serifless"
x = "straight-serifless"
y = "cursive-serifless"
z = "curly-serifless"
lower-pi = "small-capital"
zero = "tall-reverse-slashed-cutout"
one = "no-base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "upright-flat"
six = "straight-bar"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "hex-low"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "large-contour"
guillemet = "curly"
number-sign = "upright"
ampersand = "lower-open"
at = "threefold-solid-inner"
dollar = "open-cap"
percent = "rings-continuous-slash-also-connected"
question = "smooth"
pilcrow = "low"
lig-ltgteq = "flat"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.MeraIosevka.ligations]
inherits = "haskell"

[buildPlans.MeraIosevka.weights.Normal]
shape = 500
menu = 500
css = 500

[buildPlans.MeraIosevka.weights.Bold]
shape = 800
menu = 800
css = 800

[buildPlans.MeraIosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"
