[colors.primary]
background = "#101013"
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"


# [font.offset]
# x = -1
# y = -5

[window]
opacity = 0.82

[window.dimensions]
columns = 110
lines = 25

[window.padding]
x = 20
y = 20
