[colors.primary]
background = "#101013"
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "IosevkaTermSlab Nerd Font"
style = "Regular"

# [font.offset]
# x = -1
# y = -5

[window]
opacity = 0.82

[window.dimensions]
columns = 110
lines = 25

[window.padding]
x = 20
y = 20
